#ifndef INCLUDED_COOENGINE_GRAPHICS_PRECOMPILED_H
#define INCLUDED_COOENGINE_GRAPHICS_PRECOMPILED_H

#include "Common.h"

#include <Math/Inc/CooMath.h>

#endif // !INCLUDED_COOENGINE_GRAPHICS_PRECOMPILED_H
